version: '3'

services:
  app_nginx:
    build: ./infra/common/nginx
    volumes:
      - ./infra/common/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro,delegated
      - ./infra/common/nginx/conf/conf.d:/etc/nginx/conf.d:ro,delegated
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - app_php

  app_php:
    build: .
    volumes:
      - ./codebase:/app:delegated
    working_dir: /app
    environment:
      - APP_DB_HOST=app_mysql
      - APP_DB_PORT=3306
      - APP_DB_USER=app_mss
      - APP_DB_PASSWORD=123456
      - APP_DB_NAME=app_dev
    depends_on:
      - app_mysql

  app_mysql:
    restart: unless-stopped
    image: mysql:8.0
    env_file:
      - ./infra/local/mysql/.env
    environment:
      - MYSQL_USER=app_mss
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=app_dev
    volumes:
      - ./infra/local/mysql/data:/var/lib/mysql:delegated
      - ./infra/local/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,delegated
    ports:
      - '33061:3306'
